openapi: 3.0.3
info:
  title: Example API
  version: 1.0.0

paths:
  /api/v1/auth/registration/:
    post:
      description: Создание нового пользователя
      operationId: registration
      tags:
        - authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationRequest'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthenticationResponse"
        '400':
          description: Неправильный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '404':
          description: Неверный логин или пароль
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '409':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/v1/auth/login/:
    description: Авторизация пользователя
    post:
      operationId: login
      tags:
        - authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthenticationResponse"
        '400':
          description: Неправильный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '404':
          description: Неверный логин или пароль
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '409':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/v1/document/{id}:
    description: Получить документ по индентификатору
    get:
      operationId: getDocument
      tags:
        - document
      parameters:
        - name: id
          in: path
          description: documentId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentDto"
        '400':
          description: Неправильный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '404':
          description: Карточка не найдена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '409':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/v1/document/update/{id}:
    description: Обновление документа
    put:
      operationId: updateDocument
      tags:
        - document
      parameters:
        - name: id
          in: path
          description: documentId
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestDocumentDto"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentDto"
        '400':
          description: Неправильный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '404':
          description: Карточка не найдена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '409':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/v1/document/create/:
    description: Создание нового документа
    post:
      operationId: createDocument
      tags:
        - document
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestDocumentDto"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentDto"
        '400':
          description: Неправильный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '404':
          description: Карточка не найдена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '409':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/v1/document/approve/{id}:
    description: Поставить решение/утверждение по документу
    post:
      operationId: createApprove
      tags:
        - approval
      parameters:
        - name: id
          in: path
          description: documentId
          required: true
          schema:
            type: integer
            format: int64
        - name: ApprovalDecision
          in: query
          description: ApprovalDecision
          required: true
          schema:
            $ref: "#/components/schemas/ApprovalDecision"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApprovalDto"
        '400':
          description: Неправильный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '404':
          description: Карточка не найдена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '409':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/v1/document/approve/update/{id}:
    description: Обновить решение/утверждение по документу
    post:
      operationId: updateApprove
      tags:
        - approval
      parameters:
        - name: id
          in: path
          description: documentId
          required: true
          schema:
            type: integer
            format: int64
        - name: ApprovalDecision
          in: query
          description: ApprovalDecision
          required: true
          schema:
            $ref: "#/components/schemas/ApprovalDecision"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApprovalDto"
        '400':
          description: Неправильный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '404':
          description: Карточка не найдена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '409':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/v1/user/{id}:
    description: Получить пользователя по индентификатору
    get:
      operationId: getUser
      tags:
        - user
      parameters:
        - name: id
          in: path
          description: UserID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDto"
        '400':
          description: Неправильный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '409':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        timestamp:
          type: string
          format: date-time
        code:
          type: integer

    DocumentDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        dateStart:
          type: string
          format: date-time
        dateEnd:
          type: string
          format: date-time
        authors:
          type: array
          items:
            $ref: '#/components/schemas/UserDto'
        experts:
          type: array
          items:
            $ref: '#/components/schemas/UserDto'
        approvals:
          type: array
          items:
            $ref: "#/components/schemas/ApprovalDto"

    RequestDocumentDto:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        dateStart:
          type: string
          format: date-time
        dateEnd:
          type: string
          format: date-time
        authors:
          type: array
          items:
            $ref: '#/components/schemas/RequestId'
        experts:
          type: array
          items:
            $ref: '#/components/schemas/RequestId'

    ApprovalDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        documentId:
          type: integer
          format: int64
        expert:
          $ref: '#/components/schemas/UserDto'
        decision:
          $ref: "#/components/schemas/ApprovalDecision"
        decidedAt:
          type: string
          format: date-time

    ApprovalDecision:
      type: string
      description: Решение эксперта
      enum:
        - PENDING
        - APPROVED
        - REJECTED

    UserDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        role:
          type: string

    RegistrationRequest:
      type: object
      properties:
        lastName:
          type: string
        firstName:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: string

    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

    AuthenticationResponse:
      type: object
      properties:
        jwt:
          type: string

    RequestId:
      type: object
      properties:
        id:
          type: integer
          format: int64