openapi: 3.0.3
info:
  title: Example API
  version: 1.0.0

paths:
  /card/{id}:
    get:
      operationId: getCard
      tags:
        - card
      parameters:
        - name: id
          in: path
          description: CardID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CardDto"
        '400':
          description: Неправильный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDto"
        '404':
          description: Карточка не найдена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDto"

  /user/{id}:
    get:
      operationId: getUser
      tags:
        - user
      parameters:
        - name: id
          in: path
          description: UserID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDto"
        '400':
          description: Неправильный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDto"
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDto"


components:
  schemas:
    ErrorResponseDto:
      type: object
      properties:
        message:
          type: string
        timestamp:
          type: string
          format: date-time
        code:
          type: integer

    CardDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        dateStart:
          type: string
          format: date-time
        dateEnd:
          type: string
          format: date-time
        users:
          type: array
          items:
            $ref: '#/components/schemas/UserDto'

    UserDto:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        role:
          type: string